# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Biomech (Rajagopal2015) robot configuration.

Gold-standard biomechanical humanoid produced by the ``projects/biomech`` fitting
pipeline (a Windows-native port of Nimble's marker/dynamics fitters). The MJCF asset
``mjcf/biomech_rajagopal.xml`` is generated by
``biomech.export.protomotions_robot.write_biomech_asset`` from the fitted
``SkeletonSpec`` (regenerate it after refitting a subject). The exporter splits every
multi-DOF OpenSim joint into a chain of massless dummy bodies, so the simulator body set
is larger than the 20 anatomical bodies; use
``biomech.export.protomotions_robot.build_simbody_motion`` to produce motion clips whose
body order matches this robot exactly.

Control gains here are a uniform PD **starting point** (the fitted MJCF carries no
actuator gains); tune per-joint gains against measured GRF in the dynamics-refinement
milestone. The control type is Newton's native ``BUILT_IN_PD`` (as used by every shipped
ProtoMotions robot on the Newton simulator).
"""

from dataclasses import dataclass, field
import os
from typing import Dict, List

from protomotions.components.pose_lib import ControlInfo
from protomotions.robot_configs.base import (
    ControlConfig,
    ControlType,
    RobotAssetConfig,
    RobotConfig,
    SimulatorParams,
)
from protomotions.simulator.newton.config import NewtonSimParams


# Uniform PD starting point (natural-frequency based, to be tuned in dynamics refinement).
_NATURAL_FREQ = 10.0 * 2.0 * 3.141592653589793  # 10 Hz
_DAMPING_RATIO = 2.0
_ARMATURE = 0.01
_STIFFNESS = _ARMATURE * _NATURAL_FREQ**2
_DAMPING = 2.0 * _DAMPING_RATIO * _ARMATURE * _NATURAL_FREQ


def _asset_config() -> RobotAssetConfig:
    """Resolve the exact generated subject asset before kinematics are extracted."""
    stem = os.environ.get("BIOMECH_ASSET_STEM", "biomech_rajagopal")
    if not stem or stem != os.path.basename(stem) or stem.endswith(".xml"):
        raise ValueError(
            "BIOMECH_ASSET_STEM must be a file stem without directories or .xml, "
            f"got {stem!r}"
        )
    return RobotAssetConfig(
        asset_root=os.environ.get(
            "BIOMECH_ASSET_ROOT", "protomotions/data/assets"
        ),
        asset_file_name=f"mjcf/{stem}.xml",
        self_collisions=False,
    )


@dataclass
class BiomechRobotConfig(RobotConfig):
    common_naming_to_robot_body_names: Dict[str, List[str]] = field(
        default_factory=lambda: {
            "all_left_foot_bodies": ["calcn_l", "toes_l", "talus_l"],
            "all_right_foot_bodies": ["calcn_r", "toes_r", "talus_r"],
            "all_left_hand_bodies": ["hand_l"],
            "all_right_hand_bodies": ["hand_r"],
            # Rajagopal2015 has no dedicated head body; the trunk body stands in.
            "head_body_name": ["torso"],
            "torso_body_name": ["torso"],
        }
    )

    trackable_bodies_subset: List[str] = field(
        default_factory=lambda: [
            "pelvis",
            "torso",
            "femur_r",
            "tibia_r",
            "calcn_r",
            "femur_l",
            "tibia_l",
            "calcn_l",
            "hand_r",
            "hand_l",
        ]
    )

    default_root_height: float = 0.94
    anchor_body_name: str = "torso"

    asset: RobotAssetConfig = field(
        default_factory=_asset_config
    )

    control: ControlConfig = field(
        default_factory=lambda: ControlConfig(
            control_type=ControlType.BUILT_IN_PD,
            override_control_info={
                ".*": ControlInfo(
                    stiffness=_STIFFNESS,
                    damping=_DAMPING,
                    armature=_ARMATURE,
                    effort_limit=300.0,
                    velocity_limit=40.0,
                ),
                r"walker_knee_[rl]__(translation[12]|rotation[23])": ControlInfo(
                    stiffness=0.0,
                    damping=0.0,
                    actuated=False,
                ),
            },
        )
    )

    simulation_params: SimulatorParams = field(
        default_factory=lambda: SimulatorParams(
            newton=NewtonSimParams(fps=200, decimation=4),
        )
    )
