# SPDX-FileCopyrightText: Copyright (c) 2025-2026 The ProtoMotions Developers
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
from dataclasses import dataclass, field

from protomotions.robot_configs.base import RobotAssetConfig
from protomotions.robot_configs.ms_human_lower import MSHumanLowerRobotConfig


@dataclass
class MSHumanLowerS003RobotConfig(MSHumanLowerRobotConfig):
    """Subject-specific S003 scaled MS-Human lower-body skeleton.

    The asset is generated by ``data/scripts/scale_ms_human_to_subject.py`` from
    the base simplified MS-Human-700 MJCF and the initial static frames in
    ``c3dproto/S003.c3d``.
    """

    default_root_height: float = 1.0

    asset: RobotAssetConfig = field(
        default_factory=lambda: RobotAssetConfig(
            asset_file_name="mjcf/ms_human_700/MS-Human-700-Locomotion-S003.xml",
            usd_asset_file_name=None,
        )
    )
