# SPDX-License-Identifier: MIT

"""Tests for the elastic-foundation calibration (biomech.contact.calibration, M6).

Validates that ``(k_bed, c_bed, mu)`` can be recovered from a measured GRF trajectory
generated by the model itself (self-consistency), under prescribed kinematics:

- static/pressed foot -> recovers k (and c),
- sliding foot -> recovers mu,
- the calibration drives the force residual down and lands near ground truth,
- the Warp backend recovers the same parameters (skipped without CUDA).

No pytest dependency: run ``python projects/biomech/run_tests.py``.
"""

from __future__ import annotations

import numpy as np

from biomech.contact.calibration import (
    CalibrationConfig,
    CalibrationTarget,
    calibrate_elastic_foundation,
    calibrate_hydroelastic,
)
from biomech.contact.elastic_foundation import (
    ElasticFoundationParams,
    evaluate_contact,
    sample_flat_sole,
)
from biomech.tests import SkipTest

_QID = np.array([0.0, 0.0, 0.0, 1.0])


def _require_warp_cuda():
    try:
        import warp as wp  # noqa: F401
    except Exception as exc:  # noqa: BLE001
        raise SkipTest(f"warp not available: {exc}")
    if not wp.is_cuda_available():
        raise SkipTest("no CUDA device available for warp")


def _synthetic_stance(n=30, seed=0):
    """A foot pressing into the ground and sliding forward (loaded throughout)."""
    rng = np.random.default_rng(seed)
    # penetration ramps 1->4 mm, small forward slide, small vertical bob
    depth = np.linspace(0.001, 0.004, n)
    pos = np.zeros((n, 3))
    pos[:, 0] = np.linspace(0.0, 0.05, n)  # slide +x
    pos[:, 2] = -depth  # ground_z=0
    quat = np.tile(_QID, (n, 1))
    linvel = np.zeros((n, 3))
    linvel[:, 0] = 0.5  # sliding
    linvel[:, 2] = np.gradient(pos[:, 2])  # penetration-rate signal for c
    angvel = np.zeros((n, 3))
    return pos, quat, linvel, angvel


def _make_target(sole, truth, pos, quat, linvel, angvel):
    pred = evaluate_contact(sole, truth, pos, quat, linvel, angvel, backend="numpy")
    return CalibrationTarget(grf=pred.grf.copy(), cop=pred.cop.copy())


def test_recovers_stiffness_and_friction():
    sole = sample_flat_sole(0.22, 0.09, 8, 4)
    truth = ElasticFoundationParams(k_bed=4.0e6, c_bed=2.0e4, mu=0.7, v_eps=1e-3)
    pos, quat, linvel, angvel = _synthetic_stance(n=40)
    target = _make_target(sole, truth, pos, quat, linvel, angvel)

    init = ElasticFoundationParams(k_bed=1.0e6, c_bed=1.0e3, mu=0.3, v_eps=1e-3)
    res = calibrate_elastic_foundation(
        sole, pos, quat, linvel, angvel, target, init_params=init, backend="numpy",
        config=CalibrationConfig(max_iters=60),
    )

    # cost strictly decreased and force residual is tiny
    assert res.cost_history[-1] < res.cost_history[0]
    fpeak = np.abs(target.grf[:, 2]).max()
    assert res.force_rms < 1e-3 * fpeak
    # parameters recovered (k, mu tightly; c is weaker but close)
    assert abs(res.params.k_bed - truth.k_bed) / truth.k_bed < 1e-2
    assert abs(res.params.mu - truth.mu) < 1e-2
    assert abs(res.params.c_bed - truth.c_bed) / truth.c_bed < 0.1


def test_recovers_pure_stiffness_static():
    sole = sample_flat_sole(0.2, 0.1, 6, 4)
    truth = ElasticFoundationParams(k_bed=6.0e6, c_bed=0.0, mu=0.0, v_eps=1e-3)
    n = 12
    depth = np.linspace(0.001, 0.003, n)
    pos = np.zeros((n, 3))
    pos[:, 2] = -depth
    quat = np.tile(_QID, (n, 1))
    linvel = np.zeros((n, 3))
    angvel = np.zeros((n, 3))
    target = _make_target(sole, truth, pos, quat, linvel, angvel)

    init = ElasticFoundationParams(k_bed=2.0e6, c_bed=1.0e3, mu=0.1, v_eps=1e-3)
    res = calibrate_elastic_foundation(
        sole, pos, quat, linvel, angvel, target, init_params=init, backend="numpy"
    )
    assert abs(res.params.k_bed - truth.k_bed) / truth.k_bed < 1e-2
    fpeak = np.abs(target.grf[:, 2]).max()
    assert res.vertical_rms < 1e-3 * fpeak


def test_params_stay_positive():
    sole = sample_flat_sole(0.2, 0.1, 6, 4)
    truth = ElasticFoundationParams(k_bed=3.0e6, c_bed=1.0e4, mu=0.5)
    pos, quat, linvel, angvel = _synthetic_stance(n=20)
    target = _make_target(sole, truth, pos, quat, linvel, angvel)
    # start far from truth, low iters -> verify floors respected regardless
    init = ElasticFoundationParams(k_bed=1.0e4, c_bed=0.0, mu=0.01)
    res = calibrate_elastic_foundation(
        sole, pos, quat, linvel, angvel, target, init_params=init, backend="numpy",
        config=CalibrationConfig(max_iters=10, k_floor=1e3, c_floor=0.0, mu_floor=1e-3),
    )
    assert res.params.k_bed >= 1e3
    assert res.params.c_bed >= 0.0
    assert res.params.mu >= 1e-3


def test_calibration_warp_backend():
    _require_warp_cuda()
    sole = sample_flat_sole(0.22, 0.09, 10, 5)
    truth = ElasticFoundationParams(k_bed=4.0e6, c_bed=1.5e4, mu=0.65, v_eps=1e-3)
    pos, quat, linvel, angvel = _synthetic_stance(n=40, seed=2)
    # generate target with numpy (float64) truth
    target = _make_target(sole, truth, pos, quat, linvel, angvel)

    init = ElasticFoundationParams(k_bed=1.5e6, c_bed=2.0e3, mu=0.3, v_eps=1e-3)
    res = calibrate_elastic_foundation(
        sole, pos, quat, linvel, angvel, target, init_params=init, backend="warp",
        config=CalibrationConfig(max_iters=60),
    )
    # warp is float32; looser tolerances
    assert abs(res.params.k_bed - truth.k_bed) / truth.k_bed < 5e-2
    assert abs(res.params.mu - truth.mu) < 5e-2


def test_hydroelastic_calibration_recovers_params():
    from biomech.contact.hydroelastic import (
        HydroelasticParams,
        evaluate_contact as he_eval,
    )

    sole = sample_flat_sole(0.22, 0.09, 8, 4)
    truth = HydroelasticParams(
        k_bed=4.0e6, stiffen_b=0.0, hc_alpha=3.0, mu_d=0.6, mu_s=0.6,
        v_stribeck=0.05, v_eps=1e-3,
    )
    # data with a VARYING penetration rate so k and hc_alpha are separately identifiable
    # (constant vn makes force = k*d + (k*alpha)*d*vn collinear -> only the product is
    # observable). Depth stays positive; vn (=-v.z) sweeps a range.
    n = 40
    depth = np.linspace(0.001, 0.004, n)
    pos = np.zeros((n, 3))
    pos[:, 0] = np.linspace(0.0, 0.05, n)  # slide +x for friction
    pos[:, 2] = -depth
    quat = np.tile(_QID, (n, 1))
    linvel = np.zeros((n, 3))
    linvel[:, 0] = 0.5  # sliding
    linvel[:, 2] = -np.linspace(0.05, 0.5, n)  # vn = 0.05..0.5, varies across frames
    angvel = np.zeros((n, 3))
    pred = he_eval(sole, truth, pos, quat, linvel, angvel, backend="numpy")
    target = CalibrationTarget(grf=pred.grf.copy(), cop=pred.cop.copy())

    init = HydroelasticParams(
        k_bed=1.0e6, stiffen_b=0.0, hc_alpha=0.5, mu_d=0.3, mu_s=0.6,
        v_stribeck=0.05, v_eps=1e-3,
    )
    res = calibrate_hydroelastic(
        sole, pos, quat, linvel, angvel, target, init_params=init,
        free_params=("k_bed", "hc_alpha", "mu_d"), backend="numpy",
        config=CalibrationConfig(max_iters=80),
    )
    assert res.cost_history[-1] < res.cost_history[0]
    fpeak = np.abs(target.grf[:, 2]).max()
    assert res.force_rms < 5e-3 * fpeak
    assert abs(res.params.k_bed - truth.k_bed) / truth.k_bed < 2e-2
    assert abs(res.params.mu_d - truth.mu_d) < 2e-2
    assert abs(res.params.hc_alpha - truth.hc_alpha) < 0.3
    # held params untouched
    assert res.params.mu_s == init.mu_s
    assert res.params.v_stribeck == init.v_stribeck


def test_aggregate_objective_robust_to_kinematic_noise():
    """With zero-mean noise on the (reconstructed) kinematics, the aggregate objective
    recovers stiffness far better than the per-frame objective.

    The measured GRF is generated from *clean* kinematics (ground truth); we then add
    unbiased vertical noise to the kinematics fed to the calibration (mimicking cm-scale
    reconstruction jitter) and fit ``k_bed`` both ways. Per-frame least squares suffers
    errors-in-variables attenuation; the sub-bin-averaged aggregate objective averages
    the noise out.
    """
    from biomech.contact.hydroelastic import (
        HydroelasticParams,
        evaluate_contact as he_eval,
    )

    sole = sample_flat_sole(0.22, 0.09, 8, 4)
    truth = HydroelasticParams(k_bed=5.0e6, stiffen_b=0.0, hc_alpha=0.0,
                               mu_d=0.0, mu_s=0.0, v_stribeck=0.05, v_eps=1e-3)
    n = 120
    depth = np.linspace(0.002, 0.005, n)  # 2..5 mm, all patches stay in contact
    pos = np.zeros((n, 3))
    pos[:, 2] = -depth
    quat = np.tile(_QID, (n, 1))
    linvel = np.zeros((n, 3))
    angvel = np.zeros((n, 3))

    clean = he_eval(sole, truth, pos, quat, linvel, angvel, backend="numpy")
    target = CalibrationTarget(grf=clean.grf.copy())

    # noisy reconstructed kinematics: 0.8 mm zero-mean vertical jitter (< min depth)
    rng = np.random.default_rng(2)
    pos_noisy = pos.copy()
    pos_noisy[:, 2] += rng.normal(0.0, 0.8e-3, n)

    init = HydroelasticParams(k_bed=1.0e6, stiffen_b=0.0, hc_alpha=0.0,
                              mu_d=0.0, mu_s=0.0, v_stribeck=0.05, v_eps=1e-3)

    r_pf = calibrate_hydroelastic(
        sole, pos_noisy, quat, linvel, angvel, target,
        init_params=init, free_params=("k_bed",), backend="numpy",
        config=CalibrationConfig(max_iters=60, horizontal_weight=0.0,
                                 fz_threshold=1.0, objective="perframe"),
    )
    r_agg = calibrate_hydroelastic(
        sole, pos_noisy, quat, linvel, angvel, target,
        init_params=init, free_params=("k_bed",), backend="numpy",
        config=CalibrationConfig(max_iters=60, horizontal_weight=0.0,
                                 fz_threshold=1.0, objective="aggregate", agg_bins=4),
    )

    err_pf = abs(r_pf.params.k_bed - truth.k_bed) / truth.k_bed
    err_agg = abs(r_agg.params.k_bed - truth.k_bed) / truth.k_bed
    # per-frame is attenuated by the noise; aggregate stays close to truth
    assert err_agg < err_pf
    assert err_agg < 0.02
